import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {site,roles,socials} from './data/site';
import {projects,experience,education,certifications,awards,skills,reviews} from './data/content';
import './styles.css';

const Icon=({children})=><span className="icon" aria-hidden="true">{children}</span>;
const Section=({id,kicker,title,children,sub})=><section id={id} className="section"><div className="section-head"><div><span className="kicker">{kicker}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}</div></div>{children}</section>;

function Nav(){const [open,setOpen]=useState(false); const links=[['About','about'],['Experience','experience'],['Projects','projects'],['Skills','skills'],['Reviews','reviews'],['Education','education'],['Contact','contact']]; return <header className="nav"><a className="brand" href="#home" onClick={()=>setOpen(false)}><span className="brand-mark">AF</span><span><b>Arslan's Portfolio</b><small>Full Stack-MERN Developer</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">☰</button><nav className={open?'nav-links open':'nav-links'}>{links.map(([x,id])=><a key={id} href={'#'+id} onClick={()=>setOpen(false)}>{x}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setOpen(false)}>Let’s talk ↗</a></nav></header>}

function Hero(){const [role,setRole]=useState(0);useEffect(()=>{const t=setInterval(()=>setRole(r=>(r+1)%roles.length),2600);return()=>clearInterval(t)},[]);return <section id="home" className="hero"><div className="hero-copy"><span className="eyebrow">CODE • DESIGN • INNOVATION</span><h1>I’m <em>ARSLAN FAYYAZ</em></h1><p className="lead"> A versatile Full Stack MERN Developer, Creative Developer and UI/UX Designer passionate about building modern digital experiences. I work across frontend and backend development, responsive UI/UX, APIs, databases, Git/GitHub, Generative AI and software solutions.</p><div className="role-line">Currently crafting as <span>{roles[role]}</span></div><div className="hero-actions"><a className="btn primary" href="#projects">Explore my work ↗</a><a className="btn ghost" href="/Arslan-Fayyaz-CV.pdf" download>Download CV ↓</a><a className="btn ghost" href="#contact">Contact me</a></div><div className="mini-stats"><div><b>15+</b><span>Projects</span></div><div><b>9</b><span>Experience</span></div><div><b>20+</b><span>Certificates</span></div></div></div><div className="scene" aria-label="Decorative 3D developer scene"><div className="orb orb-a"></div><div className="orb orb-b"></div><div className="ring ring-a"></div><div className="ring ring-b"></div><div className="cube"><div>React . Node.js</div><div>UI/UX</div><div>AI</div></div>><div className="float-card fc-one">✦ <b>Creative UI/UX</b><small>Design.Prototyping.Responsive UI</small></div><div className="float-card fc-two">⌘ <b>AI & Innovation</b><small>Generative AI . Automation . AI Tools</small></div></div></section>}

function About(){return <Section id="about" kicker="01 / About" title="A developer with a designer’s eye" sub="A balanced mix of engineering, visual thinking and hands-on learning."><div className="about-grid"><div className="portrait"><div className="portrait-glow"></div><div className="portrait-placeholder"><span>AF</span><small>Drop your photo in <b>public/profile.jpg</b><div className="about-copy"><p>I work across frontend development, UI/UX design, generative AI and software quality. My focus is building experiences that feel clear, useful and memorable — without sacrificing performance.</p><div className="about-pills"><span>Problem Solver</span><span>UI/UX Mindset</span><span>Full Stack</span><span>AI Curious</span></div><div className="quote">“Good interfaces disappear into the experience — they just make the work feel easier.”</div><a className="text-link" href={site.voiceflow} target="_blank" rel="noreferrer">Meet my AI assistant ↗</a></div></div></Section>}

function Experience(){return <Section id="experience" kicker="02 / Experience" title="Experience that keeps evolving" sub="Internships, professional roles and hands-on work across design, development, sales and QA."><div className="timeline">{experience.map((e,i)=><article className="timeline-item" key={i}><div className="dot"></div><div className="time-card"><div className="time-top"><span>{e.dates}</span><b>{e.company}</b></div><h3>{e.role}</h3><small>{e.type} · {e.location}</small><p>{e.description}</p></div></article>)}</div></Section>}

function Projects(){return <Section id="projects" kicker="03 / Selected work" title="Projects with a purpose" sub="A showcase of frontend builds, UI/UX work, GenAI concepts and practical tools."><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p.title}><div className="project-art"><span>0{i+1}</span><div className="project-orbit"></div><strong>{p.category}</strong></div><div className="project-body"><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{p.github?<a className="text-link" href={p.github} target="_blank" rel="noreferrer">View on GitHub ↗</a>:<span className="muted">Project record</span>}</div></article>)}</div></Section>}

function Skills(){return <Section id="skills" kicker="04 / Toolkit" title="Tools I build with" sub="A practical stack spanning product design, frontend, full stack development and AI." ><div className="skill-cloud">{skills.map(([s,c])=><div className="skill" key={s}><span>{s}</span><small>{c}</small></div>)}</div></Section>}

function Reviews(){const [idx,setIdx]=useState(0);const timer=useRef();const start=()=>{clearInterval(timer.current);timer.current=setInterval(()=>setIdx(i=>(i+1)%reviews.length),5600)};useEffect(()=>{start();return()=>clearInterval(timer.current)},[]);const next=()=>{setIdx(i=>(i+1)%reviews.length);start()};const prev=()=>{setIdx(i=>(i-1+reviews.length)%reviews.length);start()};return <Section id="reviews" kicker="05 / Recognition" title="Recognition, in their own words" sub="Original screenshots from companies and professionals. The carousel moves automatically — you can also swipe or use the controls."><div className="review-wrap" onMouseEnter={()=>clearInterval(timer.current)} onMouseLeave={start}><button className="review-arrow left" onClick={prev}>←</button><div className="review-window"><div className="review-track" style={{transform:`translateX(-${idx*100}%)`}}>{reviews.map((r,i)=><article className="review-slide" key={r.company+i}><div className="review-image"><img src={r.image} alt={`${r.company} recognition for Arslan Fayyaz`} loading={i<2?'eager':'lazy'}/></div><div className="review-meta"><span>{r.label}</span><h3>{r.company}</h3><p>{r.text}</p></div></article>)}</div></div><button className="review-arrow right" onClick={next}>→</button><div className="review-dots">{reviews.map((r,i)=><button key={i} className={i===idx?'active':''} onClick={()=>{setIdx(i);start()}} aria-label={`Show review ${i+1}`}></button>)}</div></div></Section>}

function Education(){return <Section id="education" kicker="06 / Education" title="Education & credentials"><div className="two-col"><div className="stack">{education.map((e,i)=><article className="edu-card" key={i}><span>{e.dates}</span><h3>{e.degree}</h3><b>{e.institute}</b><small>{e.location} · {e.grade}</small></article>)}</div><div className="stack"><div className="panel"><h3>Certifications</h3><div className="cert-list">{certifications.map((c,i)=><div className="cert" key={i}><span>✓</span><div><b>{c[0]}</b><small>{c[1]} · {c[2]}</small></div></div>)}</div></div><div className="panel award"><span className="award-icon">✦</span><div><small>{awards[0].date}</small><h3>{awards[0].title}</h3><b>{awards[0].organization}</b><p>{awards[0].description}</p></div></div></div></div></Section>}

function Contact(){const [sent,setSent]=useState(false);const submit=(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=encodeURIComponent('Portfolio inquiry — '+f.get('name'));const body=encodeURIComponent(`Name: ${f.get('name')}\nEmail: ${f.get('email')}\n\n${f.get('message')}`);window.location.href=`mailto:${site.email}?subject=${subject}&body=${body}`;setSent(true)};return <Section id="contact" kicker="07 / Contact" title="Have an idea? Let’s build it." sub="Use the form or reach out directly. The default form opens your email client; connect a form endpoint later if you want direct server-side delivery."><div className="contact-grid"><div className="contact-card"><span className="eyebrow">START A CONVERSATION</span><h3>Let’s turn a rough idea into something people can use.</h3><p>Available for frontend development, UI/UX, portfolio websites, GenAI concepts and selected freelance work.</p><div className="map-card"><div><b>Based in</b><span>{site.location}</span></div><a className="map-btn" href={site.mapsUrl} target="_blank" rel="noreferrer">Open Google Maps ↗</a></div><div className="contact-links"><a href={`mailto:${site.email}`}>✉ {site.email}</a><a href="https://wa.me/923103321891" target="_blank" rel="noreferrer">◉ WhatsApp: 0310 3321891</a><a href={site.mapsUrl} target="_blank" rel="noreferrer">⌖ Township, Sukkur, Sindh ↗</a></div></div><form className="contact-form" onSubmit={submit}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Message<textarea name="message" required rows="6" placeholder="Tell me about your project..."></textarea></label><button className="btn primary" type="submit">Send message ↗</button>{sent&&<small className="form-note">Your email app should open with the message prepared.</small>}</form></div></Section>}

function Footer(){return <footer><div><b>Arslan Fayyaz</b><span>Full Stack • UX/UI • Creative Development</span></div><div className="footer-socials">{socials.map(([n,u,ic])=><a key={n} href={u} target={u.startsWith('http')?'_blank':undefined} rel="noreferrer" title={n}>{ic}</a>)}</div><small>© {new Date().getFullYear()} Arslan Fayyaz. Built with React + Vite.</small></footer>}
function App(){return <><Nav/><main><Hero/><About/><Experience/><Projects/><Skills/><Reviews/><Education/><Contact/></main><Footer/><a className="whatsapp" href="https://wa.me/923103321891" target="_blank" rel="noreferrer" aria-label="WhatsApp">◉</a></>}
createRoot(document.getElementById('root')).render(<App/>);
